---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

```{python slideshow={'slide_type': 'skip'}, editable=TRUE}
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
```

```{python slideshow={'slide_type': 'skip'}}
# %matplotlib inline
plt.rcParams["figure.figsize"] = [12,8]
```

<!-- #region slideshow={"slide_type": "slide"} editable=true -->
## Training  Bayes
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} editable=true -->
As we have shown in the previous lectures training a Bayes classifier amounts to finding the conditional probability distributions of the features $\mathbf{f}$ given the class label $c$. 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$P(\mathbf{F}=\mathbf{f}|C=c)$$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
In case of the Naive bayes classifier the $n_f$ features are conditionally independent 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$P(\mathbf{F}=\mathbf{f}|C=c)=\prod_{i=0}^{n_f-1} P(F_i=f_i|C=c)$$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
so we can estimate   probality distribution  for each feature separately. 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "slide"} -->
### Categorical features
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
In case of categorical features each $x_i$ has a finite $m_i$  number of possible values (categories) that, without any loss of generality we can  assume, take values $0,\ldots,m_i-1$. In the same way we  will assume that the class labels take $n_c$ integer values $c=0,\ldots,n_c-1$. 

So for each feature we have  to estimate  $n_c\times m_i$ probabilities 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$p^{(c)}_{ij} = P(F_i = j|C = c)$$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
Of course they are not all idependent. Normalisation requires
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$\sum_{j=0}^{m_i-1} p^{(c)}_{ij}=1,\quad i=0,\ldots,n_f,\; c=0,\ldots,n_c$$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
Let $\mathbf{X}$ denote the $n_s \times n_f$ matrix of training data where $n_s$ is the number of samples. So $X_{hi}$ denotes the value of the ith   feature in  sample $h$. Let  $y_h$ denote the corresponding label
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "slide"} -->
$$X_{hi} \in \{0,\ldots,m_i-1\},\quad  y_h \in \{0,\ldots,n_c-1\},\quad h = 0,\ldots,n_s-1$$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
Let's introduce some more notation. $n_c$ will denote the number of samples belonging to class $c$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$n^{c}=\sum_{h=0}^{n_s-1}\delta_{y_h,c},\qquad \delta_{a,b}=
\begin{cases}
1 & a=b\\
0 & a\neq b
\end{cases}$$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
and $n^{(c)}_{ij}$ the number of samples of class $c$ with feature $i$ equal to  $j$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$n^{(c)}_{ij} = \displaystyle
\sum_{h=0}^{n_s-1} \delta_{X_{hi},j}\delta_{y_h,c}
$$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
To estimate the probabilities we will use a smoothed estimator 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$p^{(c)}_{ij} = \frac{n^{(c)}_{ij}+\alpha}{n^c+m_i\alpha} $$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
where $\alpha\ge 0$ is a smoothing parameter. The use of  non-zero smoothing parameter ensures a non-vanishing probability even when $n^{(c)}_{ij}=0$. 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "slide"} -->
## Example: Car evaluation data set
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
As an example we will use the [car evaluation dataset](http://archive.ics.uci.edu/ml/datasets/Car+Evaluation) from [UCI Machine Learning repository](http://archive.ics.uci.edu/ml/). It contains 1728 samples with six atttributes (features) each. The class label is the evaluation of the car: $\{unacc, acc, good, vgood\}$.
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
All six parameters are categorical and the data contains exactly one sample for each possible combination of attributes values (in this respect this is quite peculiar dataset).
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
As before we will use pandas to read and proccess the data.
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
cars_data = pd.read_csv("../../Data/Cars/car_data.csv", names=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'])
```

```{python slideshow={'slide_type': 'fragment'}}
cars_data.head()
```

```{python slideshow={'slide_type': 'fragment'}}
cars_data.info()
```

<!-- #region slideshow={"slide_type": "skip"} -->
Method `groupby`  divides the data frame into groups based on the value of the given colum(s)
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
cars_by_class = cars_data.groupby('class')
```

<!-- #region slideshow={"slide_type": "skip"} -->
The size of each group can be calculated using method `size`
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
cars_by_class.size()
```

<!-- #region slideshow={"slide_type": "skip"} -->
As we can see the classes are not very well ballanced with relatively small number of cars in two best  classes.  So I have decided to join those two classes together introducing a new classification
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
def bargain(c):
    if c in ['good', 'vgood']:
        return 'good'
    elif c=='acc':
        return 'fair'
    else:
        return 'bad'
```

```{python slideshow={'slide_type': '-'}}
cars_data['bargain'] = cars_data['class'].apply(bargain)
cars_data = cars_data.drop('class',axis=1)
```

<!-- #region slideshow={"slide_type": "skip"} -->
We start by dividing the data set into training and testing. 
<!-- #endregion -->

```{python slideshow={'slide_type': 'skip'}}
from sklearn.model_selection import train_test_split
```

```{python slideshow={'slide_type': 'skip'}}
seed = 678565
```

```{python slideshow={'slide_type': 'slide'}}
cars_train, cars_test = train_test_split(cars_data, train_size=0.75, random_state=seed)
```

```{python slideshow={'slide_type': '-'}}
cars_train['bargain'].value_counts()
```

```{python slideshow={'slide_type': '-'}}
cars_test['bargain'].value_counts()
```

<!-- #region slideshow={"slide_type": "skip"} -->
Function `train_test_split` has an option to _stratify_ data based on the values of one colum
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
cars_train, cars_test = train_test_split(cars_data, train_size=0.75, stratify=cars_data['bargain'],
                                         random_state = seed)
```

<!-- #region slideshow={"slide_type": "skip"} -->
In this way the split was done separately for each  class label. That way we obtain as a result slightly more balanced sets
<!-- #endregion -->

```{python slideshow={'slide_type': '-'}}
cars_train['bargain'].value_counts()
```

```{python slideshow={'slide_type': '-'}}
cars_test['bargain'].value_counts()
```

<!-- #region slideshow={"slide_type": "skip"} -->
We will use the Naive Bayes.
There are many ways that we can calculate the estimators. We can start by grouping the dataframe according to  feature values
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
cars_training_grouped = cars_train.groupby(['bargain', 
                                            'buying',
                                            'maint',
                                            'doors', 
                                            'persons', 
                                            'lug_boot',
                                            'safety'])
```

<!-- #region slideshow={"slide_type": "skip"} -->
and count the size of each group
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
group_counts=cars_training_grouped.size()
```

```{python}
group_counts
```

<!-- #region slideshow={"slide_type": "skip"} -->
The `sum` method can make a partial sums which we can use to extract $n^{c}_{ij}$ values
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
# The level argument list the levels not summed over i.e. left in the result.
group_counts.groupby(level = ['bargain', 'buying'] ).sum()
```

<!-- #region slideshow={"slide_type": "skip"} -->
and finally calculate the probabilities
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
(group_counts.groupby(level = ['bargain', 'buying'] ).sum() +1 )/(group_counts.groupby(level='bargain').sum()+4)
```

<!-- #region slideshow={"slide_type": "slide"} -->
## Scikit-learn
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
However if you look closely you will notice one problem: the 'good' class does not contain any values for 'high' and 'vhigh'  attribute values! That means of course that they are zero, but it complicates the calculations. Instead of fixing this by hand we will use the tools from the [scikit-learn](https://scikit-learn.org/stable/index.html) library. This library has a class implementing just what we need
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
from sklearn.naive_bayes import CategoricalNB
```

```{python slideshow={'slide_type': 'fragment'}}
cnb = CategoricalNB(alpha=1)
```

<!-- #region slideshow={"slide_type": "skip"} -->
However this classifier requires the  class labels and attributes to be  integer numbers counted from zero. Fortunatelly scikit-learn also includes a class for converting from labels to ordinals:
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
from sklearn.preprocessing import  OrdinalEncoder
```

```{python slideshow={'slide_type': 'fragment'}, editable=TRUE}
features_encoder = OrdinalEncoder(dtype='int32')
features_encoder.fit(cars_train)
train_encoded = pd.DataFrame(features_encoder.transform(cars_train), columns=features_encoder.get_feature_names_out())
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
np.bincount(train_encoded.iloc[:,-1])
```

```{python slideshow={'slide_type': 'slide'}, editable=TRUE}
cnb.fit(train_encoded.iloc[:,:-1], train_encoded.iloc[:,-1])
```

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
We can view the learned probabilities of this classifier  using its `feature_log_prob` attribute:
<!-- #endregion -->

```{python editable=TRUE, slideshow={'slide_type': ''}}
features_encoder.categories_[-1]
```

```{python editable=TRUE, slideshow={'slide_type': ''}}

```

```{python editable=TRUE, slideshow={'slide_type': ''}}

```

```{python slideshow={'slide_type': 'fragment'}, editable=TRUE}
pd.DataFrame(np.exp( cnb.feature_log_prob_[0], ), 
             columns=features_encoder.categories_[0], index=features_encoder.categories_[-1]).style.set_caption(f"{features_encoder.feature_names_in_[0]}")
```

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
Comparing with our calculations we see a almost perfect agreement. Mowever we get all four probabilities in the last line like required. The two values are not zero because of smoothing. 
<!-- #endregion -->

```{python editable=TRUE, slideshow={'slide_type': ''}}
from sklearn.metrics import accuracy_score
accuracy_score(train_encoded.iloc[:,-1], cnb.predict(train_encoded.iloc[:,0:-1]), normalize=True)
```

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
After training the classifier we can use it to  make predictions on the test set
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}, editable=TRUE}
test_encoded = pd.DataFrame(features_encoder.transform(cars_test), columns=features_encoder.get_feature_names_out())
encoded_test_class = test_encoded.iloc[:,-1]
```

```{python slideshow={'slide_type': 'fragment'}, editable=TRUE}
predicted_test_class = cnb.predict(test_encoded.iloc[:,:-1])
```

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
and test them
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}, editable=TRUE}
from sklearn.metrics import accuracy_score
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
accuracy_score(encoded_test_class, predicted_test_class, normalize=True)
```

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
Actually the classifier has a method for predicting and measuring accuracy
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}, editable=TRUE}
cnb.score(test_encoded.iloc[:,:-1], encoded_test_class)
```

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
which unsuprisingly gives same results
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
As a last check I will look at the class distribution in the predicted and real labels. As it may happen that with unbalanced  classes  one class can be e.g. totaly misclassified without affecting accuracy. 
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}, editable=TRUE}
np.bincount(predicted_test_class.astype('int64'))
```

```{python slideshow={'slide_type': '-'}, editable=TRUE}
np.bincount(encoded_test_class.astype('int64'))
```

<!-- #region slideshow={"slide_type": "slide"} editable=true -->
## Multiclass metrics
<!-- #endregion -->

```{python editable=TRUE, slideshow={'slide_type': ''}}
from sklearn.metrics import multilabel_confusion_matrix, confusion_matrix, ConfusionMatrixDisplay
```

<!-- #region slideshow={"slide_type": "slide"} editable=true -->
### Confusion matrix
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} editable=true -->
The accuracy  generalises intuitively to non-binary classification.  The confusion matrix also generalises to this case.  
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}, editable=TRUE}
pred = predicted_test_class
true = encoded_test_class
```

```{python slideshow={'slide_type': 'slide'}, editable=TRUE}
confusion_matrix(true, pred)
```

```{python slideshow={'slide_type': 'slide'}, editable=TRUE}
ConfusionMatrixDisplay.from_predictions(true, pred, normalize='true', 
                                        display_labels=features_encoder.categories_[-1]);
```

<!-- #region slideshow={"slide_type": "slide"} editable=true -->
### Averaging 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
Other metrics are defined only for binary classification problem as they rely on a 2x2 confusion matrix.  A way to generalise them to multiclass classification it to treat a $k$ class classifcation problem as $k$ binary classification problems: class   $C_i$ against the rest. We combine the final score out of binary metrics for each binary classification. 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment", "slideshow": {"slide_type": "slide"}} -->
<table style="font-size:1.5em;">
<tr> <th>         </th> <th colspan=2>predicted</th></tr>
    <tr> <th>actual</th> <th>N  </th> <th>P  </th> <th>total</th></tr>
    <tr> <th> N       </th> <td>TN </td> <td>FP </td> <td>N</td></tr>
    <tr> <th> P       </th> <td>FN </td> <td>TP </td> <td>P</td></tr>
</table>
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
def stat(y_true, y_pred, c):
    lbl_true = np.where(y_true==c,1,0)
    lbl_pred = np.where(y_pred==c,1,0)
    (TN,FP),(FN,TP) = confusion_matrix(lbl_true, lbl_pred)    
    return TP, FP,FN, TN
```

```{python slideshow={'slide_type': 'slide'}}
for i in range(3):
    print( stat(true,pred, i))
```

<!-- #region slideshow={"slide_type": "skip"} -->
Once we have the statistics for each binary classifier we can combine the together. We will consider _micro_ and _macro_ averaging. 
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
mcf = multilabel_confusion_matrix(true, pred)
print(mcf)
```

<!-- #region slideshow={"slide_type": "slide"} -->
### Micro averaging
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
In micro averaging we first calculate the summary values of TP, FP, TN and TN and use them to calculate the total score. 
We will start with _recall_ which is just another name for true positives rate.
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$Recall_\mu = \frac{\sum_i TP_i}{\sum_i(TP_i+FN_i)}$$
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
num = 0
den = 0
for i in range(3):
    ((tn, fp), (fn, tp)) =  mcf[i]
    num += tp
    den += tp+fn
recall_mu = num/den    
print(num, den, recall_mu   )
```

<!-- #region slideshow={"slide_type": "slide"} -->
$$Precision_\mu = \frac{\sum_i TP_i}{\sum_i(TP_i+FP_i)}$$
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
num = 0
den = 0
for i in range(3):
    ((tn, fp), (fn, tp)) =  mcf[i]
    num += tp
    den += tp+fp
precision_mu = num/den    
print(num, den, precision_mu    )
```

<!-- #region slideshow={"slide_type": "skip"} -->
and $F_1$ is then  harmonic mean of the two
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "slide"} -->
$$F_\mu = 2\cdot\frac{Precision_\mu\cdot Recall_\mu}{Precision_\mu + Recall_\mu}$$
<!-- #endregion -->

```{python}
print(2*precision_mu*recall_mu/(precision_mu+recall_mu))
```

<!-- #region tags=["problem"] slideshow={"slide_type": "slide"} -->
#### Problem
<!-- #endregion -->

<!-- #region tags=["problem"] slideshow={"slide_type": "-"} -->
  Show that $Recall_\mu$ = $Precision_\mu = Accuracy$
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} -->
There is no surprise that scikit-learn library has functions to calculate those metrics
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
from sklearn.metrics import *
```

```{python slideshow={'slide_type': '-'}}
print(
    recall_score(encoded_test_class, predicted_test_class, average='micro'),
    precision_score(encoded_test_class, predicted_test_class, average='micro'),
    f1_score(encoded_test_class, predicted_test_class, average='micro'))
```

<!-- #region slideshow={"slide_type": "slide"} -->
### Macro averaging
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
With macro averaging we  calculate  score for each binary classifier separately and average them. So for recall
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "fragment"} -->
$$Recall_M = \frac{1}{k}\sum_{i=0}^{k-1}\frac{TP_i}{TP_i+FN_i}$$
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
tot = 0
for i in range(3):
    ((tn, fp), (fn, tp)) =  mcf[i]
    tot +=tp/(tp+fn)
rec = tot/3    
print(rec)
```

```{python slideshow={'slide_type': 'fragment'}}
recall_score(encoded_test_class, predicted_test_class, average='macro')
```

<!-- #region slideshow={"slide_type": "skip"} -->
and for precision
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "slide"} editable=true -->
$$Precision_M = \frac{1}{k}\sum_{i=0}^{k-1}\frac{TP_i}{TP_i+FP_i}$$
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
tot = 0
for i in range(3):
    ((tn, fp), (fn, tp)) =  mcf[i]
    tot +=tp/(tp+fp)
prec =  tot/3   
print(prec)
```

```{python slideshow={'slide_type': 'fragment'}}
precision_score(encoded_test_class, predicted_test_class, average='macro')
```

<!-- #region slideshow={"slide_type": "skip"} -->
and $F_1$ score is
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "slide"} -->
$$F_1 = \frac{1}{k}\sum_{i=0}^{k-1}\frac{2\cdot TP_i}{TP_i+FP_i +TP_i +FN_i}$$
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}}
tot = 0
for i in range(3):
    ((tn, fp), (fn, tp)) =  mcf[i]
    tot +=2 * tp/(tp+fp+tp+fn)
f =  tot/3   
print(f)
```

```{python}
f1_score(encoded_test_class, predicted_test_class, average='macro')
```

<!-- #region slideshow={"slide_type": "slide"} -->
### Weighted averaging 
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "skip"} editable=true -->
And finally the weighted averaging is like macro averaging but we  weight the average by the support of each class _i.e._ the number of labels of each class. E.g. for precision
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "slide"} editable=true -->
$$Precision_M = \sum_{i=0}^{k-1}\frac{TP_i}{TP_i+FP_i} \frac{P_k}{\sum_k P_i}$$
<!-- #endregion -->

```{python slideshow={'slide_type': 'fragment'}, editable=TRUE}
tot = 0
den = 0
for i in range(3):
    tp, fp, fn, tn =  stat(true,pred, i)
    tot +=tp/(tp+fp) *(tp+fn)
    den += (tp+fn)
prec = tot/den
print(prec)
```

```{python slideshow={'slide_type': 'fragment'}}
precision_score(encoded_test_class, predicted_test_class, average='weighted')
```

<!-- #region tags=["problem"] slideshow={"slide_type": "slide"} -->
#### Problem 
<!-- #endregion -->

<!-- #region tags=["problem"] slideshow={"slide_type": "-"} -->
 Show that weighted averaging for recall gives same result as micro averaging.
<!-- #endregion -->

<!-- #region slideshow={"slide_type": "notes"} -->
As you may have guessed scikit-learn library has some convenient functions that calculate those metrics at once.
<!-- #endregion -->

```{python slideshow={'slide_type': 'slide'}}
from sklearn.metrics import precision_recall_fscore_support,  classification_report
```

```{python slideshow={'slide_type': 'fragment'}}
precision_recall_fscore_support(encoded_test_class, predicted_test_class, beta = 2, average = 'macro')
```

```{python slideshow={'slide_type': 'fragment'}}
print(classification_report(encoded_test_class, predicted_test_class))
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
features_encoder.categories_
```
